---
- name: Undefined variable example
  hosts: localhost
  gather_facts: false

  tasks:
    - name: This task will fail
      ansible.builtin.debug:
        var: item
      loop: "{{ host_objects }}"

...
