---
- name: Loops
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Loop intro
      debug:
        msg: "{{ item }}"  # use double quotes
      loop:
        - red
        - green
        - blue

...
